
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by generate-portfolio-data.js

export type FieldData = {
  title: string
  description: string
  images: string[]
  thumbnail: string
}

export type SubProject = {
  title: string
  thumbnail: string
  images: string[]
  description: string[]
  fields: Record<string, FieldData>
}

export type CategoryData = {
  title: string
  description: string
  thumbnail: string
  projects: Record<string, SubProject>
}

export const portfolioData: Record<string, CategoryData> = {
  "kidswear": {
    "title": "Custom Title",
    "description": "Short description",
    "thumbnail": "/images/portfolio/kidswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "thumbnail": "/images/portfolio/kidswear/project1/thumbnail.jpg",
        "images": [],
        "description": [
          "Short description"
        ],
        "fields": {
          "consulting": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/kidswear/project1/consulting/image1.jpg",
              "/images/portfolio/kidswear/project1/consulting/image2.jpg",
              "/images/portfolio/kidswear/project1/consulting/image3.jpg"
            ],
            "thumbnail": "/images/portfolio/kidswear/project1/consulting/thumbnail.jpg"
          },
          "design": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/kidswear/project1/design/image1.jpg",
              "/images/portfolio/kidswear/project1/design/image2.jpg",
              "/images/portfolio/kidswear/project1/design/image3.jpg"
            ],
            "thumbnail": "/images/portfolio/kidswear/project1/design/thumbnail.jpg"
          },
          "production": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/kidswear/project1/production/image1.jpg",
              "/images/portfolio/kidswear/project1/production/image2.jpg",
              "/images/portfolio/kidswear/project1/production/image3.jpg"
            ],
            "thumbnail": "/images/portfolio/kidswear/project1/production/thumbnail.jpg"
          },
          "styling": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/kidswear/project1/styling/image1.jpg",
              "/images/portfolio/kidswear/project1/styling/image2.jpg",
              "/images/portfolio/kidswear/project1/styling/image3.jpg"
            ],
            "thumbnail": "/images/portfolio/kidswear/project1/styling/thumbnail.jpg"
          }
        }
      }
    }
  },
  "menswear": {
    "title": "Custom Title",
    "description": "Short description",
    "thumbnail": "/images/portfolio/menswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "thumbnail": "/images/portfolio/menswear/project1/thumbnail.jpg",
        "images": [],
        "description": [
          "Short description"
        ],
        "fields": {
          "consulting": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/menswear/project1/consulting/image1.jpg",
              "/images/portfolio/menswear/project1/consulting/image2.jpg"
            ],
            "thumbnail": "/images/portfolio/menswear/project1/consulting/thumbnail.jpg"
          },
          "design": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/menswear/project1/design/image1.jpg",
              "/images/portfolio/menswear/project1/design/image2.jpg"
            ],
            "thumbnail": "/images/portfolio/menswear/project1/design/thumbnail.jpg"
          },
          "production": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/menswear/project1/production/image1.jpg",
              "/images/portfolio/menswear/project1/production/image2.jpg"
            ],
            "thumbnail": "/images/portfolio/menswear/project1/production/thumbnail.jpg"
          },
          "styling": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/menswear/project1/styling/image1.jpg",
              "/images/portfolio/menswear/project1/styling/image2.jpg"
            ],
            "thumbnail": "/images/portfolio/menswear/project1/styling/thumbnail.jpg"
          }
        }
      }
    }
  },
  "womenswear": {
    "title": "Custom Title",
    "description": "Short description",
    "thumbnail": "/images/portfolio/womenswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "thumbnail": "/images/portfolio/womenswear/project1/thumbnail.jpg",
        "images": [],
        "description": [
          "Short description"
        ],
        "fields": {
          "consulting": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/womenswear/project1/consulting/image1.jpg",
              "/images/portfolio/womenswear/project1/consulting/image2.jpg",
              "/images/portfolio/womenswear/project1/consulting/image3.jpg",
              "/images/portfolio/womenswear/project1/consulting/image4.jpg"
            ],
            "thumbnail": "/images/portfolio/womenswear/project1/consulting/thumbnail.jpg"
          },
          "design": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/womenswear/project1/design/image1.jpg",
              "/images/portfolio/womenswear/project1/design/image2.jpg",
              "/images/portfolio/womenswear/project1/design/image3.jpg",
              "/images/portfolio/womenswear/project1/design/image4.jpg"
            ],
            "thumbnail": "/images/portfolio/womenswear/project1/design/thumbnail.jpg"
          },
          "production": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/womenswear/project1/production/image1.jpg",
              "/images/portfolio/womenswear/project1/production/image2.jpg",
              "/images/portfolio/womenswear/project1/production/image3.jpg",
              "/images/portfolio/womenswear/project1/production/image4.jpg"
            ],
            "thumbnail": "/images/portfolio/womenswear/project1/production/thumbnail.jpg"
          },
          "styling": {
            "title": "Custom Title",
            "description": "Short description",
            "images": [
              "/images/portfolio/womenswear/project1/styling/image1.jpg",
              "/images/portfolio/womenswear/project1/styling/image2.jpg",
              "/images/portfolio/womenswear/project1/styling/image3.jpg",
              "/images/portfolio/womenswear/project1/styling/image4.jpg"
            ],
            "thumbnail": "/images/portfolio/womenswear/project1/styling/thumbnail.jpg"
          }
        }
      }
    }
  }
}
