// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by generate-portfolio-data.js

export type FieldData = {
  title: string
  description: string
  thumbnail: string
  hero: string
  images: string[]
}

export type SubProject = {
  title: string
  description: string
  thumbnail: string
  fields: Record<string, FieldData>
}

export type CategoryData = {
  title: string
  description: string
  thumbnail: string
  projects: Record<string, SubProject>
}

export const portfolioData: Record<string, CategoryData> = {
  "kidswear": {
    "title": "KIDSWEAR",
    "description": "",
    "thumbnail": "/images/portfolio/kidswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/kidswear/project1/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/kidswear/project1/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project1/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/kidswear/project1/design/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project1/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/kidswear/project1/production/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project1/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/kidswear/project1/styling/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project1/styling/thumbnail.jpg",
            "images": []
          }
        }
      },
      "project2": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/kidswear/project2/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/kidswear/project2/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project2/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/kidswear/project2/design/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project2/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/kidswear/project2/production/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project2/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/kidswear/project2/styling/thumbnail.jpg",
            "hero": "/images/portfolio/kidswear/project2/styling/thumbnail.jpg",
            "images": []
          }
        }
      }
    }
  },
  "menswear": {
    "title": "MENSWEAR",
    "description": "",
    "thumbnail": "/images/portfolio/menswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/menswear/project1/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/menswear/project1/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project1/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/menswear/project1/design/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project1/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/menswear/project1/production/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project1/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/menswear/project1/styling/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project1/styling/thumbnail.jpg",
            "images": []
          }
        }
      },
      "project2": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/menswear/project2/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/menswear/project2/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project2/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/menswear/project2/design/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project2/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/menswear/project2/production/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project2/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/menswear/project2/styling/thumbnail.jpg",
            "hero": "/images/portfolio/menswear/project2/styling/thumbnail.jpg",
            "images": []
          }
        }
      }
    }
  },
  "womenswear": {
    "title": "WOMENSWEAR",
    "description": "",
    "thumbnail": "/images/portfolio/womenswear/thumbnail.jpg",
    "projects": {
      "project1": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/womenswear/project1/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/womenswear/project1/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project1/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/womenswear/project1/design/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project1/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/womenswear/project1/production/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project1/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/womenswear/project1/styling/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project1/styling/thumbnail.jpg",
            "images": []
          }
        }
      },
      "project2": {
        "title": "Custom Title",
        "description": "Short description",
        "thumbnail": "/images/portfolio/womenswear/project2/thumbnail.jpg",
        "fields": {
          "consulting": {
            "title": "Concept & Research",
            "description": "Where ideas take root.",
            "thumbnail": "/images/portfolio/womenswear/project2/consulting/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project2/consulting/thumbnail.jpg",
            "images": []
          },
          "design": {
            "title": "Design Development",
            "description": "Sketching dreams into form.",
            "thumbnail": "/images/portfolio/womenswear/project2/design/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project2/design/thumbnail.jpg",
            "images": []
          },
          "production": {
            "title": "Materials & Technicals",
            "description": "From vision to fabric reality.",
            "thumbnail": "/images/portfolio/womenswear/project2/production/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project2/production/thumbnail.jpg",
            "images": []
          },
          "styling": {
            "title": "Final Presentation",
            "description": "The story unveiled in style.",
            "thumbnail": "/images/portfolio/womenswear/project2/styling/thumbnail.jpg",
            "hero": "/images/portfolio/womenswear/project2/styling/thumbnail.jpg",
            "images": []
          }
        }
      }
    }
  }
}
